export enum Grade {
    GAV = "GAV",
    GND = "GND",
    SGT = "SGT",
    SGT_C = "SGT_C",
    ADJ = "ADJ",
    ADC = "ADC",
    MJR = "MJR",
    SLT = "SLT",
    LTN = "LTN",
    CNE = "CNE",
    COM = "COM",
    LCL = "LCL",
    COL = "COL",
    GBR = "GBR",
    GDI = "GDI",
    GCA = "GCA",
    GA = "GA",
    PC = "PC",
  }